const express=require('express');
const crypto=require('crypto');
const catalyst=require('zcatalyst-sdk-node');
const router=express.Router();

const USERS='Portal_Users',SESSIONS='Portal_Sessions',COOKIE='lms_session';
const CREATOR_OWNER=process.env.CREATOR_OWNER||'demo2rlogicssolutions';
const CREATOR_APP=process.env.CREATOR_APP||'loan-management-backend-system';
const CREATOR_API_BASE=process.env.CREATOR_API_BASE||'https://www.zohoapis.eu/creator/v2.1';
const ZOHO_ACCOUNTS_URL=process.env.ZOHO_ACCOUNTS_URL||'https://accounts.zoho.eu';
const APPLICATION_REPORT=process.env.CREATOR_LOAN_APPLICATION_REPORT||'loan_application_Report';
const APPROVAL_REPORT=process.env.CREATOR_LOAN_APPROVAL_REPORT||'loan_approval_Report';
const hash=t=>crypto.createHash('sha256').update(t).digest('hex');
const safe=v=>String(v).replace(/'/g,"''");
const z=req=>catalyst.initialize(req);
async function query(req,q){return(await z(req).zcql().executeZCQLQuery(q))||[]}
async function token(){const body=new URLSearchParams({refresh_token:process.env.ZOHO_REFRESH_TOKEN,client_id:process.env.ZOHO_CLIENT_ID,client_secret:process.env.ZOHO_CLIENT_SECRET,grant_type:'refresh_token'});const r=await fetch(`${ZOHO_ACCOUNTS_URL}/oauth/v2/token`,{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:body.toString()});const d=await r.json().catch(()=>({}));if(!r.ok||!d.access_token)throw Object.assign(new Error('Unable to connect to Zoho Creator.'),{statusCode:502,oauth:{httpStatus:r.status,error:d.error||'token_exchange_failed'}});return d.access_token}
async function currentUser(req){const session=req.cookies?.[COOKIE];if(!session)return null;const rows=await query(req,`SELECT * FROM ${SESSIONS} WHERE TOKEN_HASH='${safe(hash(session))}'`);if(!rows.length)return null;const s=rows[0][SESSIONS]||rows[0];if(s.REVOKED||new Date(s.EXPIRES_AT)<=new Date())return null;const users=await query(req,`SELECT PORTAL_USER_ID,EMAIL,CREATOR_CUSTOMER_ID,ACCOUNT_STATUS FROM ${USERS} WHERE PORTAL_USER_ID='${safe(s.PORTAL_USER_ID)}'`);const u=users[0]?.[USERS]||users[0];return u?.ACCOUNT_STATUS==='ACTIVE'&&u.CREATOR_CUSTOMER_ID?u:null}
function idOf(v){if(v==null)return'';if(typeof v==='object')return String(v.ID||v.id||v.value||v.zc_display_value||'');return String(v)}
function textOf(v){if(v==null)return'';if(typeof v==='object')return String(v.zc_display_value||v.display_value||v.name||v.value||v.ID||'');return String(v)}
function matches(v,id){if(v==null)return false;if(Array.isArray(v))return v.some(x=>matches(x,id));if(typeof v==='object')return[v.ID,v.id,v.value,v.zc_display_value].some(x=>String(x||'')===String(id));return String(v)===String(id)}
async function report(name){const a=await token();const r=await fetch(`${CREATOR_API_BASE}/data/${CREATOR_OWNER}/${CREATOR_APP}/report/${name}`,{headers:{Authorization:`Zoho-oauthtoken ${a}`}});const d=await r.json().catch(()=>({}));if(!r.ok||(!Array.isArray(d.data)&&d.code!==3000))throw Object.assign(new Error('Unable to load Creator data.'),{statusCode:502,creator:d});return d.data||[]}
async function patchApplication(id,status){const a=await token();const r=await fetch(`${CREATOR_API_BASE}/data/${CREATOR_OWNER}/${CREATOR_APP}/report/${APPLICATION_REPORT}/${id}`,{method:'PATCH',headers:{Authorization:`Zoho-oauthtoken ${a}`,'Content-Type':'application/json'},body:JSON.stringify({data:{application_status:status},result:{message:true}})});const d=await r.json().catch(()=>({}));if(!r.ok||!(d.code===3000||Array.isArray(d.result)))throw Object.assign(new Error('Unable to sync application status.'),{statusCode:502,creator:d})}
router.post('/:id/sync',async(req,res)=>{const requestId=`SYNC-${crypto.randomUUID()}`;try{const user=await currentUser(req);if(!user)return res.status(401).json({message:'Please sign in again.'});const target=String(req.params.id||'');const apps=await report(APPLICATION_REPORT);const app=apps.find(r=>matches(r.customer,user.CREATOR_CUSTOMER_ID)&&(idOf(r.ID)===target||textOf(r.application_id)===target));if(!app)return res.status(404).json({message:'Application not found.'});const approvals=await report(APPROVAL_REPORT);const approval=approvals.find(r=>matches(r.customer,user.CREATOR_CUSTOMER_ID)&&matches(r.loan_application,idOf(app.ID)));if(!approval)return res.json({ok:true,synced:false,status:textOf(app.application_status)||'Submitted'});const decision=textOf(approval.approval_status).trim();const lower=decision.toLowerCase();let status=null;if(lower==='approved')status='Approved';else if(lower==='rejected')status='Rejected';else if(lower.includes('pending'))status='Pending Approval';if(status&&textOf(app.application_status)!==status){await patchApplication(idOf(app.ID),status)}res.json({ok:true,synced:Boolean(status),status:status||textOf(app.application_status)||'Submitted',approval:{id:idOf(approval.ID),approvalStatus:decision,approvedAmount:Number(approval.approved_amount||0),approvedTenure:Number(approval.approved_tenure||0),approvedInterestRate:Number(approval.approved_interest_rate||0),approvedBy:textOf(approval.approved_by),approvalDate:textOf(approval.approval_date),approvalRemarks:textOf(approval.approval_remarks),rejectionReason:textOf(approval.rejection_reason)}})}catch(e){console.error('[APPROVAL_SYNC_FAILED]',JSON.stringify({requestId,message:e.message,oauth:e.oauth||null,creator:e.creator||null}));res.status(e.statusCode||500).json({message:'Unable to sync approval decision.',requestId})}});
module.exports=router;
