const express=require('express');
const crypto=require('crypto');
const catalyst=require('zcatalyst-sdk-node');
const router=express.Router();
const USERS='Portal_Users',SESSIONS='Portal_Sessions',COOKIE='lms_session';
const OWNER=process.env.CREATOR_OWNER||'demo2rlogicssolutions';
const APP=process.env.CREATOR_APP||'loan-management-backend-system';
const API=process.env.CREATOR_API_BASE||'https://www.zohoapis.eu/creator/v2.1';
const ACCOUNTS=process.env.ZOHO_ACCOUNTS_URL||'https://accounts.zoho.eu';
const MASTER_REPORT=process.env.CREATOR_LOAN_MASTER_REPORT||'loan_master_Report';
const EMI_REPORT=process.env.CREATOR_EMI_SCHEDULE_REPORT||'emi_schedule_Report';
const APPLICATION_REPORT=process.env.CREATOR_LOAN_APPLICATION_REPORT||'loan_application_Report';
let cache={value:null,expiresAt:0};
const hash=t=>crypto.createHash('sha256').update(t).digest('hex');
const safe=v=>String(v).replace(/'/g,"''");
const z=req=>catalyst.initialize(req);
async function query(req,q){return(await z(req).zcql().executeZCQLQuery(q))||[]}
async function token(){if(cache.value&&Date.now()<cache.expiresAt)return cache.value;const body=new URLSearchParams({refresh_token:process.env.ZOHO_REFRESH_TOKEN,client_id:process.env.ZOHO_CLIENT_ID,client_secret:process.env.ZOHO_CLIENT_SECRET,grant_type:'refresh_token'});const r=await fetch(`${ACCOUNTS}/oauth/v2/token`,{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:body.toString()});const d=await r.json().catch(()=>({}));if(!r.ok||!d.access_token)throw Object.assign(new Error('Unable to connect to Zoho Creator.'),{statusCode:502});cache={value:d.access_token,expiresAt:Date.now()+45*60*1000};return cache.value}
async function user(req){const s=req.cookies?.[COOKIE];if(!s)return null;const rows=await query(req,`SELECT * FROM ${SESSIONS} WHERE TOKEN_HASH='${safe(hash(s))}'`);if(!rows.length)return null;const session=rows[0][SESSIONS]||rows[0];if(session.REVOKED||new Date(session.EXPIRES_AT)<=new Date())return null;const users=await query(req,`SELECT PORTAL_USER_ID,EMAIL,CREATOR_CUSTOMER_ID,ACCOUNT_STATUS FROM ${USERS} WHERE PORTAL_USER_ID='${safe(session.PORTAL_USER_ID)}'`);const u=users[0]?.[USERS]||users[0];return u?.ACCOUNT_STATUS==='ACTIVE'&&u.CREATOR_CUSTOMER_ID?u:null}
function id(v){if(v==null)return'';if(typeof v==='object')return String(v.ID||v.id||v.value||v.zc_display_value||'');return String(v)}
function text(v){if(v==null)return'';if(typeof v==='object')return String(v.zc_display_value||v.display_value||v.name||v.value||v.ID||'');return String(v)}
function match(v,target){if(v==null)return false;if(Array.isArray(v))return v.some(x=>match(x,target));if(typeof v==='object')return[v.ID,v.id,v.value,v.zc_display_value].some(x=>String(x||'')===String(target));return String(v)===String(target)}
async function report(name){const t=await token();const r=await fetch(`${API}/data/${OWNER}/${APP}/report/${name}`,{headers:{Authorization:`Zoho-oauthtoken ${t}`}});const d=await r.json().catch(()=>({}));if(!r.ok||(!Array.isArray(d.data)&&d.code!==3000))throw Object.assign(new Error(`Unable to load ${name}.`),{statusCode:502});return d.data||[]}
function parseDate(v){if(!v)return new Date(0);const raw=String(v);const m=raw.match(/^(\d{2})-([A-Za-z]{3})-(\d{4})/);if(m){const months={Jan:0,Feb:1,Mar:2,Apr:3,May:4,Jun:5,Jul:6,Aug:7,Sep:8,Oct:9,Nov:10,Dec:11};return new Date(Number(m[3]),months[m[2]],Number(m[1]))}const d=new Date(raw);return Number.isNaN(d.getTime())?new Date(0):d}
function closureDateFor(master,emis){const appId=id(master.loan_application);const rows=emis.filter(r=>match(r.loan_application,appId)&&String(text(r.payment_status)).toLowerCase()==='paid');const dates=rows.map(r=>text(r.payment_date)||text(r.due_date)).filter(Boolean).sort((a,b)=>parseDate(b)-parseDate(a));return dates[0]||text(master.Modified_Time)||text(master.disbursement_date)||''}
function summaryFor(master,emis,apps){const appId=id(master.loan_application),app=apps.find(r=>id(r.ID)===appId)||{};const mine=emis.filter(r=>match(r.loan_application,appId));const totalFromEmis=mine.filter(r=>String(text(r.payment_status)).toLowerCase()==='paid').reduce((s,r)=>s+Number(r.emi_amount||0),0);return{loanId:id(master.ID),loanApplicationId:appId,applicationId:text(app.application_id)||appId,loanType:text(app.loan_type)||text(master.loan_type)||'Loan',principalAmount:Number(master.principal_amount||0),totalPaid:Number(master.total_paid_amount||0)||Number(totalFromEmis.toFixed(2)),interestRate:Number(master.interest_rate||0),tenure:Number(master.tenure||0),closureDate:closureDateFor(master,emis),status:'Closed',emisPaid:Number(master.number_of_emis_paid||mine.length),outstandingPrincipal:Number(master.outstanding_principal||0)}}
function escPdf(v){return String(v??'').replace(/\\/g,'\\\\').replace(/\(/g,'\\(').replace(/\)/g,'\\)').replace(/[^\x20-\x7E]/g,' ')}
function money(v){return Number(v||0).toLocaleString('en-IN',{minimumFractionDigits:2,maximumFractionDigits:2})}
function makePdf(lines,ref){const content=['0.08 0.45 0.27 rg','50 735 495 60 re f','1 1 1 rg','BT /F1 20 Tf 72 770 Td (LendFlow Finance) Tj ET','0.06 0.08 0.07 rg','BT /F1 16 Tf 72 700 Td (Loan Closure / No Dues Certificate) Tj ET','BT /F1 10 Tf 72 675 Td (Certificate Reference: '+escPdf(ref)+') Tj ET'];let y=640;for(const line of lines){content.push(`BT /F1 11 Tf 72 ${y} Td (${escPdf(line)}) Tj ET`);y-=27}content.push('0.10 0.64 0.39 rg','50 155 495 2 re f','0.20 0.25 0.22 rg','BT /F1 9 Tf 72 125 Td (This certificate is system generated from the customer loan records.) Tj ET','BT /F1 9 Tf 72 108 Td (It confirms that the above loan is recorded as Closed with no outstanding principal.) Tj ET');const stream=content.join('\n');const objects=[null,'<< /Type /Catalog /Pages 2 0 R >>','<< /Type /Pages /Kids [3 0 R] /Count 1 >>','<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>','<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>',`<< /Length ${Buffer.byteLength(stream)} >>\nstream\n${stream}\nendstream`];let pdf='%PDF-1.4\n',offsets=[0];for(let i=1;i<objects.length;i++){offsets[i]=Buffer.byteLength(pdf);pdf+=`${i} 0 obj\n${objects[i]}\nendobj\n`}const xref=Buffer.byteLength(pdf);pdf+=`xref\n0 ${objects.length}\n0000000000 65535 f \n`;for(let i=1;i<objects.length;i++)pdf+=`${String(offsets[i]).padStart(10,'0')} 00000 n \n`;pdf+=`trailer\n<< /Size ${objects.length} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`;return Buffer.from(pdf,'ascii')}
router.get('/summary',async(req,res)=>{const requestId=`CLOSE-${crypto.randomUUID()}`;try{const u=await user(req);if(!u)return res.status(401).json({message:'Please sign in again.'});const[masters,emis,apps]=await Promise.all([report(MASTER_REPORT),report(EMI_REPORT),report(APPLICATION_REPORT)]);const mine=masters.filter(r=>match(r.customer,u.CREATOR_CUSTOMER_ID));const closed=mine.filter(r=>String(text(r.loan_status)).toLowerCase()==='closed').map(r=>summaryFor(r,emis,apps)).sort((a,b)=>parseDate(b.closureDate)-parseDate(a.closureDate));res.json({closedLoans:closed.length,latest:closed[0]||null})}catch(e){console.error('[CLOSURE_SUMMARY_FAILED]',JSON.stringify({requestId,message:e.message}));res.status(e.statusCode||500).json({message:'Unable to load loan closure details.',requestId})}});
router.get('/certificate/:loanId',async(req,res)=>{const requestId=`CERT-${crypto.randomUUID()}`;try{const u=await user(req);if(!u)return res.status(401).json({message:'Please sign in again.'});const[masters,emis,apps]=await Promise.all([report(MASTER_REPORT),report(EMI_REPORT),report(APPLICATION_REPORT)]);const master=masters.find(r=>id(r.ID)===String(req.params.loanId)&&match(r.customer,u.CREATOR_CUSTOMER_ID));if(!master)return res.status(404).json({message:'Loan account not found.'});if(String(text(master.loan_status)).toLowerCase()!=='closed')return res.status(409).json({message:'Closure certificate is available only after the loan is closed.'});const c=summaryFor(master,emis,apps),ref=`NDC-${c.loanId}-${new Date().getFullYear()}`;const pdf=makePdf([`Customer: ${u.EMAIL}`,`Application: ${c.applicationId}`,`Loan type: ${c.loanType}`,`Principal amount: INR ${money(c.principalAmount)}`,`Total amount repaid: INR ${money(c.totalPaid)}`,`Interest rate: ${c.interestRate}%`, `Tenure: ${c.tenure} months`,`EMIs paid: ${c.emisPaid}`,`Outstanding principal: INR ${money(c.outstandingPrincipal)}`,`Loan closure date: ${c.closureDate||'Recorded as closed'}`,`Status: CLOSED - NO DUES OUTSTANDING`],ref);res.setHeader('Content-Type','application/pdf');res.setHeader('Content-Disposition',`attachment; filename="loan-closure-${c.applicationId}.pdf"`);res.setHeader('Cache-Control','private, no-store');res.send(pdf)}catch(e){console.error('[CLOSURE_CERTIFICATE_FAILED]',JSON.stringify({requestId,message:e.message}));res.status(e.statusCode||500).json({message:'Unable to generate closure certificate.',requestId})}});
module.exports=router;
