const express=require('express');
const crypto=require('crypto');
const catalyst=require('zcatalyst-sdk-node');
const router=express.Router();

const USERS='Portal_Users',SESSIONS='Portal_Sessions',COOKIE='lms_session';
const CREATOR_OWNER=process.env.CREATOR_OWNER||'demo2rlogicssolutions';
const CREATOR_APP=process.env.CREATOR_APP||'loan-management-backend-system';
const CREATOR_API_BASE=process.env.CREATOR_API_BASE||'https://www.zohoapis.eu/creator/v2.1';
const ZOHO_ACCOUNTS_URL=process.env.ZOHO_ACCOUNTS_URL||'https://accounts.zoho.eu';
const APPLICATION_REPORT=process.env.CREATOR_LOAN_APPLICATION_REPORT||'loan_application_Report';
const APPROVAL_REPORT=process.env.CREATOR_LOAN_APPROVAL_REPORT||'loan_approval_Report';
const DISBURSEMENT_REPORT=process.env.CREATOR_LOAN_DISBURSEMENT_REPORT||'loan_disbursement_Report';
const LOAN_MASTER_FORM=process.env.CREATOR_LOAN_MASTER_FORM||'loan_master';
const LOAN_MASTER_REPORT=process.env.CREATOR_LOAN_MASTER_REPORT||'loan_master_Report';

let tokenCache={value:null,expiresAt:0};
const hash=t=>crypto.createHash('sha256').update(t).digest('hex');
const safe=v=>String(v).replace(/'/g,"''");
const z=req=>catalyst.initialize(req);
async function query(req,q){return(await z(req).zcql().executeZCQLQuery(q))||[]}
async function token(){if(tokenCache.value&&Date.now()<tokenCache.expiresAt)return tokenCache.value;const body=new URLSearchParams({refresh_token:process.env.ZOHO_REFRESH_TOKEN,client_id:process.env.ZOHO_CLIENT_ID,client_secret:process.env.ZOHO_CLIENT_SECRET,grant_type:'refresh_token'});const r=await fetch(`${ZOHO_ACCOUNTS_URL}/oauth/v2/token`,{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:body.toString()});const d=await r.json().catch(()=>({}));if(!r.ok||!d.access_token)throw Object.assign(new Error('Unable to connect to Zoho Creator.'),{statusCode:502,oauth:{httpStatus:r.status,error:d.error||'token_exchange_failed'}});tokenCache={value:d.access_token,expiresAt:Date.now()+45*60*1000};return tokenCache.value}
async function currentUser(req){const session=req.cookies?.[COOKIE];if(!session)return null;const rows=await query(req,`SELECT * FROM ${SESSIONS} WHERE TOKEN_HASH='${safe(hash(session))}'`);if(!rows.length)return null;const s=rows[0][SESSIONS]||rows[0];if(s.REVOKED||new Date(s.EXPIRES_AT)<=new Date())return null;const users=await query(req,`SELECT PORTAL_USER_ID,EMAIL,CREATOR_CUSTOMER_ID,ACCOUNT_STATUS FROM ${USERS} WHERE PORTAL_USER_ID='${safe(s.PORTAL_USER_ID)}'`);const u=users[0]?.[USERS]||users[0];return u?.ACCOUNT_STATUS==='ACTIVE'&&u.CREATOR_CUSTOMER_ID?u:null}
function idOf(v){if(v==null)return'';if(typeof v==='object')return String(v.ID||v.id||v.value||v.zc_display_value||'');return String(v)}
function textOf(v){if(v==null)return'';if(typeof v==='object')return String(v.zc_display_value||v.display_value||v.name||v.value||v.ID||'');return String(v)}
function matches(v,id){if(v==null)return false;if(Array.isArray(v))return v.some(x=>matches(x,id));if(typeof v==='object')return[v.ID,v.id,v.value,v.zc_display_value].some(x=>String(x||'')===String(id));return String(v)===String(id)}
async function report(name){const a=await token();const r=await fetch(`${CREATOR_API_BASE}/data/${CREATOR_OWNER}/${CREATOR_APP}/report/${name}`,{headers:{Authorization:`Zoho-oauthtoken ${a}`}});const d=await r.json().catch(()=>({}));if(!r.ok||(!Array.isArray(d.data)&&d.code!==3000))throw Object.assign(new Error('Unable to load Creator data.'),{statusCode:502,creator:d});return d.data||[]}
async function patchApplication(id,status){const a=await token();const r=await fetch(`${CREATOR_API_BASE}/data/${CREATOR_OWNER}/${CREATOR_APP}/report/${APPLICATION_REPORT}/${id}`,{method:'PATCH',headers:{Authorization:`Zoho-oauthtoken ${a}`,'Content-Type':'application/json'},body:JSON.stringify({data:{application_status:status},result:{message:true}})});const d=await r.json().catch(()=>({}));if(!r.ok||!(d.code===3000||d.data||Array.isArray(d.result)))throw Object.assign(new Error('Unable to update application status.'),{statusCode:502,creator:d})}
function emi(principal,annualRate,months){const p=Number(principal||0),n=Math.max(1,Number(months||1)),r=Number(annualRate||0)/1200;if(!p)return 0;if(!r)return Number((p/n).toFixed(2));const x=Math.pow(1+r,n);return Number((p*r*x/(x-1)).toFixed(2))}
function nextMonth(dateText){const d=dateText?new Date(dateText):new Date();if(Number.isNaN(d.getTime()))return creatorDateTime(new Date(Date.now()+30*86400000));d.setMonth(d.getMonth()+1);return creatorDateTime(d)}
function creatorDateTime(v){const d=v instanceof Date?v:new Date(v||Date.now()),m=['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];return`${String(d.getDate()).padStart(2,'0')}-${m[d.getMonth()]}-${d.getFullYear()} ${String(d.getHours()).padStart(2,'0')}:${String(d.getMinutes()).padStart(2,'0')}:${String(d.getSeconds()).padStart(2,'0')}`}
function mapDisbursement(r){return{id:idOf(r.ID),approvedAmount:Number(r.approved_amount||0),disbursementAmount:Number(r.disbursement_amount||0),disbursementDate:textOf(r.disbursement_date),disbursementStatus:textOf(r.disbursement_status),bankAccountReference:textOf(r.bank_account_reference),transactionReference:textOf(r.transaction_reference),remarks:textOf(r.remarks)}}
function mapLoanMaster(r){return{id:idOf(r.ID),principalAmount:Number(r.principal_amount||0),interestRate:Number(r.interest_rate||0),tenure:Number(r.tenure||0),emiAmount:Number(r.emi_amount||0),disbursementDate:textOf(r.disbursement_date),loanStatus:textOf(r.loan_status),nextEmiDate:textOf(r.next_emi_date),numberOfEmisPaid:Number(r.number_of_emis_paid||0),numberOfEmisPending:Number(r.number_of_emis_pending||0),outstandingPrincipal:Number(r.outstanding_principal||0),totalPaidAmount:Number(r.total_paid_amount||0)}}

router.get('/:id',async(req,res)=>{const requestId=`DISB-${crypto.randomUUID()}`;try{const user=await currentUser(req);if(!user)return res.status(401).json({message:'Please sign in again.'});const target=String(req.params.id||'');const apps=await report(APPLICATION_REPORT);const app=apps.find(r=>matches(r.customer,user.CREATOR_CUSTOMER_ID)&&(idOf(r.ID)===target||textOf(r.application_id)===target));if(!app)return res.status(404).json({message:'Application not found.'});const appId=idOf(app.ID);const [approvals,disbursements,masters]=await Promise.all([report(APPROVAL_REPORT),report(DISBURSEMENT_REPORT),report(LOAN_MASTER_REPORT)]);const approval=approvals.find(r=>matches(r.customer,user.CREATOR_CUSTOMER_ID)&&matches(r.loan_application,appId));const disbursement=disbursements.find(r=>matches(r.customer,user.CREATOR_CUSTOMER_ID)&&matches(r.loan_application,appId));let master=masters.find(r=>matches(r.customer,user.CREATOR_CUSTOMER_ID)&&matches(r.loan_application,appId));if(disbursement&&String(textOf(disbursement.disbursement_status)).toLowerCase()==='disbursed'&&!master){if(!approval||String(textOf(approval.approval_status)).toLowerCase()!=='approved')throw Object.assign(new Error('Loan must be approved before creating loan master.'),{statusCode:409});const principal=Number(disbursement.disbursement_amount||approval.approved_amount||0),rate=Number(approval.approved_interest_rate||0),tenure=Number(approval.approved_tenure||0),emiAmount=emi(principal,rate,tenure),payload={customer:String(user.CREATOR_CUSTOMER_ID),loan_application:appId,loan_type:idOf(app.loan_type),principal_amount:principal,interest_rate:rate,tenure,emi_amount:emiAmount,disbursement_date:textOf(disbursement.disbursement_date)||creatorDateTime(),loan_status:'Active',next_emi_date:nextMonth(textOf(disbursement.disbursement_date)),number_of_emis_paid:0,number_of_emis_pending:tenure,outstanding_principal:principal,total_paid_amount:0};const a=await token();const r=await fetch(`${CREATOR_API_BASE}/data/${CREATOR_OWNER}/${CREATOR_APP}/form/${LOAN_MASTER_FORM}`,{method:'POST',headers:{Authorization:`Zoho-oauthtoken ${a}`,'Content-Type':'application/json'},body:JSON.stringify({data:payload,result:{message:true}})});const d=await r.json().catch(()=>({}));const recordId=d?.data?.ID||(Array.isArray(d.result)?d.result[0]?.data?.ID:null);if(!r.ok||!recordId)throw Object.assign(new Error('Creator rejected loan master creation.'),{statusCode:502,creator:d});master={ID:String(recordId),...payload};await patchApplication(appId,'Disbursed')}else if(disbursement&&String(textOf(disbursement.disbursement_status)).toLowerCase()==='disbursed'){await patchApplication(appId,'Disbursed')}
res.json({disbursement:disbursement?mapDisbursement(disbursement):null,loanMaster:master?mapLoanMaster(master):null})}catch(e){console.error('[DISBURSEMENT_SYNC_FAILED]',JSON.stringify({requestId,message:e.message,oauth:e.oauth||null,creator:e.creator||null}));res.status(e.statusCode||500).json({message:'Unable to load disbursement details.',requestId})}});

module.exports=router;
