const express=require('express');
const crypto=require('crypto');
const catalyst=require('zcatalyst-sdk-node');
const router=express.Router();
const USERS='Portal_Users',SESSIONS='Portal_Sessions',COOKIE='lms_session',BUCKET=process.env.STRATUS_LOAN_DOCUMENT_BUCKET||'lms-loan-documents';
const CREATOR_OWNER=process.env.CREATOR_OWNER||'demo2rlogicssolutions',CREATOR_APP=process.env.CREATOR_APP||'loan-management-backend-system',CREATOR_API_BASE=process.env.CREATOR_API_BASE||'https://www.zohoapis.eu/creator/v2.1',ZOHO_ACCOUNTS_URL=process.env.ZOHO_ACCOUNTS_URL||'https://accounts.zoho.eu',DOCUMENT_FORM=process.env.CREATOR_LOAN_DOCUMENT_FORM||'loan_document',DOCUMENT_REPORT=process.env.CREATOR_LOAN_DOCUMENT_REPORT||'loan_document_Report',APPLICATION_REPORT=process.env.CREATOR_LOAN_APPLICATION_REPORT||'loan_application_Report';
const ALLOWED=new Set(['application/pdf','image/jpeg','image/png']),MAX=10*1024*1024,hash=t=>crypto.createHash('sha256').update(t).digest('hex'),safe=v=>String(v).replace(/'/g,"''"),z=req=>catalyst.initialize(req);async function query(req,q){return(await z(req).zcql().executeZCQLQuery(q))||[]}
async function accessToken(){const body=new URLSearchParams({refresh_token:process.env.ZOHO_REFRESH_TOKEN,client_id:process.env.ZOHO_CLIENT_ID,client_secret:process.env.ZOHO_CLIENT_SECRET,grant_type:'refresh_token'}),r=await fetch(`${ZOHO_ACCOUNTS_URL}/oauth/v2/token`,{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:body.toString()}),d=await r.json().catch(()=>({}));if(!r.ok||!d.access_token)throw Object.assign(new Error('Unable to connect to Zoho Creator.'),{statusCode:502});return d.access_token}
async function currentUser(req){const token=req.cookies?.[COOKIE];if(!token)return null;const sessions=await query(req,`SELECT * FROM ${SESSIONS} WHERE TOKEN_HASH='${safe(hash(token))}'`);if(!sessions.length)return null;const s=sessions[0][SESSIONS]||sessions[0];if(s.REVOKED||new Date(s.EXPIRES_AT)<=new Date())return null;const users=await query(req,`SELECT PORTAL_USER_ID,EMAIL,CREATOR_CUSTOMER_ID,ACCOUNT_STATUS FROM ${USERS} WHERE PORTAL_USER_ID='${safe(s.PORTAL_USER_ID)}'`);if(!users.length)return null;const u=users[0][USERS]||users[0];return u.ACCOUNT_STATUS==='ACTIVE'&&u.CREATOR_CUSTOMER_ID?u:null}async function requireUser(req,res){const u=await currentUser(req);if(!u)res.status(401).json({message:'Please sign in again.'});return u}
async function report(name){const token=await accessToken(),r=await fetch(`${CREATOR_API_BASE}/data/${CREATOR_OWNER}/${CREATOR_APP}/report/${name}`,{headers:{Authorization:`Zoho-oauthtoken ${token}`}}),d=await r.json().catch(()=>({}));if(!r.ok||(!Array.isArray(d.data)&&d.code!==3000))throw Object.assign(new Error('Unable to load Creator data.'),{statusCode:502,creator:d});return d.data||[]}
function idOf(v){if(v==null)return'';if(typeof v==='object')return String(v.ID||v.id||v.value||v.zc_display_value||'');return String(v)}function textOf(v){if(v==null)return'';if(typeof v==='object')return String(v.zc_display_value||v.display_value||v.name||v.value||v.ID||'');return String(v)}function matches(v,id){if(v==null)return false;if(Array.isArray(v))return v.some(x=>matches(x,id));if(typeof v==='object')return [v.ID,v.id,v.value,v.zc_display_value].some(x=>String(x||'')===String(id));return String(v)===String(id)}
function creatorDateTime(){const d=new Date(),m=['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];return`${String(d.getDate()).padStart(2,'0')}-${m[d.getMonth()]}-${d.getFullYear()} ${String(d.getHours()).padStart(2,'0')}:${String(d.getMinutes()).padStart(2,'0')}:${String(d.getSeconds()).padStart(2,'0')}`}function cleanName(v){return String(v||'document').replace(/[^A-Za-z0-9._-]+/g,'_').slice(-100)}
async function ownedApplication(user,id){const rows=await report(APPLICATION_REPORT);return rows.find(r=>matches(r.customer,user.CREATOR_CUSTOMER_ID)&&(idOf(r.ID)===String(id)||textOf(r.application_id)===String(id)))||null}function mapDoc(r){return{id:idOf(r.ID),applicationId:idOf(r.loan_application),documentType:textOf(r.document_type),documentFile:textOf(r.document_file),status:textOf(r.document_status)||'Pending Verification',uploadedDate:textOf(r.uploaded_date),verificationRemarks:textOf(r.verification_remarks),verifiedBy:textOf(r.verified_by),verifiedDate:textOf(r.verified_date)}}
router.get('/',async(req,res)=>{try{const u=await requireUser(req,res);if(!u)return;const applicationId=String(req.query.applicationId||'').trim();const app=applicationId?await ownedApplication(u,applicationId):null;if(applicationId&&!app)return res.status(404).json({message:'Application not found.'});const appRecordId=app?idOf(app.ID):'';const rows=await report(DOCUMENT_REPORT),docs=rows.filter(r=>matches(r.customer,u.CREATOR_CUSTOMER_ID)&&(!appRecordId||matches(r.loan_application,appRecordId))).map(mapDoc);res.json({documents:docs})}catch(e){console.error('[DOCUMENT_LIST_FAILED]',e);res.status(e.statusCode||500).json({message:'Unable to load documents right now.'})}});
router.post('/upload',async(req,res)=>{let objectKey='';try{const u=await requireUser(req,res);if(!u)return;const applicationId=String(req.body.applicationId||'').trim(),documentType=String(req.body.documentType||'').trim(),fileName=cleanName(req.body.fileName),contentType=String(req.body.contentType||'').toLowerCase(),fileBase64=String(req.body.fileBase64||'');if(!applicationId||!documentType||!fileBase64)return res.status(400).json({message:'Application, document type and file are required.'});if(!ALLOWED.has(contentType))return res.status(400).json({message:'Only PDF, JPG and PNG files are allowed.'});const app=await ownedApplication(u,applicationId);if(!app)return res.status(404).json({message:'Application not found.'});const buffer=Buffer.from(fileBase64,'base64');if(!buffer.length||buffer.length>MAX)return res.status(400).json({message:'File must be between 1 byte and 10 MB.'});objectKey=`loan-documents/${u.CREATOR_CUSTOMER_ID}/${idOf(app.ID)}/${Date.now()}-${crypto.randomBytes(5).toString('hex')}-${fileName}`;const bucket=z(req).stratus().bucket(BUCKET);await bucket.putObject(objectKey,buffer,{contentType,metaData:{customer:String(u.CREATOR_CUSTOMER_ID),application:idOf(app.ID),documentType}});const payload={customer:String(u.CREATOR_CUSTOMER_ID),loan_application:idOf(app.ID),document_type:documentType,document_file:objectKey,document_status:'Pending Verification',uploaded_date:creatorDateTime()},token=await accessToken(),url=`${CREATOR_API_BASE}/data/${CREATOR_OWNER}/${CREATOR_APP}/form/${DOCUMENT_FORM}`,r=await fetch(url,{method:'POST',headers:{Authorization:`Zoho-oauthtoken ${token}`,'Content-Type':'application/json'},body:JSON.stringify({data:payload,result:{message:true}})}),d=await r.json().catch(()=>({})),first=Array.isArray(d.result)?d.result[0]:null,recordId=d?.data?.ID||first?.data?.ID;if(!r.ok||!recordId){try{await bucket.deleteObject(objectKey)}catch{}throw Object.assign(new Error('Creator rejected document metadata.'),{statusCode:502,creator:d})}res.status(201).json({ok:true,document:{id:String(recordId),...payload,fileName,contentType,size:buffer.length}})}catch(e){const requestId=`DOC-${crypto.randomUUID()}`;console.error('[DOCUMENT_UPLOAD_FAILED]',JSON.stringify({requestId,message:e.message,objectKey,creator:e.creator||null}));res.status(e.statusCode||500).json({message:'Unable to upload document.',requestId})}});
module.exports=router;
