const express=require('express');
const crypto=require('crypto');
const catalyst=require('zcatalyst-sdk-node');
const router=express.Router();

const USERS='Portal_Users',SESSIONS='Portal_Sessions',COOKIE='lms_session';
const CREATOR_OWNER=process.env.CREATOR_OWNER||'demo2rlogicssolutions';
const CREATOR_APP=process.env.CREATOR_APP||'loan-management-backend-system';
const CREATOR_API_BASE=process.env.CREATOR_API_BASE||'https://www.zohoapis.eu/creator/v2.1';
const ZOHO_ACCOUNTS_URL=process.env.ZOHO_ACCOUNTS_URL||'https://accounts.zoho.eu';
const DOCUMENT_FORM=process.env.CREATOR_LOAN_DOCUMENT_FORM||'loan_document';
const DOCUMENT_REPORT=process.env.CREATOR_LOAN_DOCUMENT_REPORT||'loan_document_Report';
const APPLICATION_REPORT=process.env.CREATOR_LOAN_APPLICATION_REPORT||'loan_application_Report';
const hash=t=>crypto.createHash('sha256').update(t).digest('hex');
const safe=v=>String(v).replace(/'/g,"''");
const z=req=>catalyst.initialize(req);
async function query(req,q){return(await z(req).zcql().executeZCQLQuery(q))||[]}
async function accessToken(){const body=new URLSearchParams({refresh_token:process.env.ZOHO_REFRESH_TOKEN,client_id:process.env.ZOHO_CLIENT_ID,client_secret:process.env.ZOHO_CLIENT_SECRET,grant_type:'refresh_token'});const r=await fetch(`${ZOHO_ACCOUNTS_URL}/oauth/v2/token`,{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:body.toString()});const d=await r.json().catch(()=>({}));if(!r.ok||!d.access_token)throw Object.assign(new Error('Unable to connect to Zoho Creator.'),{statusCode:502});return d.access_token}
async function currentUser(req){const token=req.cookies?.[COOKIE];if(!token)return null;const sessions=await query(req,`SELECT * FROM ${SESSIONS} WHERE TOKEN_HASH='${safe(hash(token))}'`);if(!sessions.length)return null;const s=sessions[0][SESSIONS]||sessions[0];if(s.REVOKED||new Date(s.EXPIRES_AT)<=new Date())return null;const users=await query(req,`SELECT PORTAL_USER_ID,EMAIL,CREATOR_CUSTOMER_ID,ACCOUNT_STATUS FROM ${USERS} WHERE PORTAL_USER_ID='${safe(s.PORTAL_USER_ID)}'`);if(!users.length)return null;const u=users[0][USERS]||users[0];return u.ACCOUNT_STATUS==='ACTIVE'&&u.CREATOR_CUSTOMER_ID?u:null}
async function requireUser(req,res){const u=await currentUser(req);if(!u)res.status(401).json({code:'AUTH_REQUIRED',message:'Please sign in again.'});return u}
async function report(name){const token=await accessToken();const r=await fetch(`${CREATOR_API_BASE}/data/${CREATOR_OWNER}/${CREATOR_APP}/report/${name}`,{headers:{Authorization:`Zoho-oauthtoken ${token}`}});const d=await r.json().catch(()=>({}));if(!r.ok||(!Array.isArray(d.data)&&d.code!==3000))throw Object.assign(new Error('Unable to load Creator data.'),{statusCode:502,creator:d});return d.data||[]}
function idOf(v){if(v==null)return'';if(typeof v==='object')return String(v.ID||v.id||v.value||v.zc_display_value||'');return String(v)}
function textOf(v){if(v==null)return'';if(typeof v==='object')return String(v.zc_display_value||v.display_value||v.name||v.value||v.ID||'');return String(v)}
function matches(v,id){if(v==null)return false;if(Array.isArray(v))return v.some(x=>matches(x,id));if(typeof v==='object')return [v.ID,v.id,v.value,v.zc_display_value].some(x=>String(x||'')===String(id));return String(v)===String(id)}
function creatorDateTime(){const d=new Date(),m=['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];return`${String(d.getDate()).padStart(2,'0')}-${m[d.getMonth()]}-${d.getFullYear()} ${String(d.getHours()).padStart(2,'0')}:${String(d.getMinutes()).padStart(2,'0')}:${String(d.getSeconds()).padStart(2,'0')}`}
async function ownedApplication(user,id){const rows=await report(APPLICATION_REPORT);return rows.find(r=>matches(r.customer,user.CREATOR_CUSTOMER_ID)&&(idOf(r.ID)===String(id)||textOf(r.application_id)===String(id)))||null}
function mapDoc(r){return{id:idOf(r.ID),customerId:idOf(r.customer),applicationId:idOf(r.loan_application),documentType:textOf(r.document_type),documentFile:textOf(r.document_file),status:textOf(r.document_status)||'Pending Verification',uploadedDate:textOf(r.uploaded_date),verificationRemarks:textOf(r.verification_remarks),verifiedBy:textOf(r.verified_by),verifiedDate:textOf(r.verified_date)}}
router.get('/',async(req,res)=>{try{const u=await requireUser(req,res);if(!u)return;const applicationId=String(req.query.applicationId||'').trim();if(applicationId&&!await ownedApplication(u,applicationId))return res.status(404).json({message:'Application not found.'});const rows=await report(DOCUMENT_REPORT);const docs=rows.filter(r=>matches(r.customer,u.CREATOR_CUSTOMER_ID)&&(!applicationId||matches(r.loan_application,applicationId))).map(mapDoc);res.json({documents:docs})}catch(e){console.error('[DOCUMENT_LIST_FAILED]',JSON.stringify({message:e.message,creator:e.creator||null}));res.status(e.statusCode||500).json({message:'Unable to load documents right now.'})}});
router.post('/',async(req,res)=>{try{const u=await requireUser(req,res);if(!u)return;const applicationId=String(req.body.applicationId||'').trim(),documentType=String(req.body.documentType||'').trim(),documentFile=String(req.body.documentFile||'').trim();if(!applicationId)return res.status(400).json({field:'applicationId',message:'Select a loan application.'});const app=await ownedApplication(u,applicationId);if(!app)return res.status(404).json({message:'Application not found.'});if(!documentType)return res.status(400).json({field:'documentType',message:'Select a document type.'});if(!documentFile)return res.status(400).json({field:'documentFile',message:'Document upload reference is required.'});const payload={customer:String(u.CREATOR_CUSTOMER_ID),loan_application:idOf(app.ID),document_type:documentType,document_file:documentFile,document_status:'Pending Verification',uploaded_date:creatorDateTime()};const token=await accessToken();const url=`${CREATOR_API_BASE}/data/${CREATOR_OWNER}/${CREATOR_APP}/form/${DOCUMENT_FORM}`;const r=await fetch(url,{method:'POST',headers:{Authorization:`Zoho-oauthtoken ${token}`,'Content-Type':'application/json'},body:JSON.stringify({data:payload,result:{message:true}})});const d=await r.json().catch(()=>({}));const first=Array.isArray(d.result)?d.result[0]:null,id=d?.data?.ID||first?.data?.ID;if(!r.ok||!id)throw Object.assign(new Error('Creator rejected document metadata.'),{statusCode:502,creator:d});res.status(201).json({ok:true,document:{id:String(id),...payload}})}catch(e){const requestId=`DOC-${crypto.randomUUID()}`;console.error('[DOCUMENT_CREATE_FAILED]',JSON.stringify({requestId,message:e.message,creator:e.creator||null}));res.status(e.statusCode||500).json({message:'Unable to save document metadata.',requestId})}});
module.exports=router;
