const express=require('express');
const crypto=require('crypto');
const catalyst=require('zcatalyst-sdk-node');
const router=express.Router();
const USERS='Portal_Users',SESSIONS='Portal_Sessions',COOKIE='lms_session';
const OWNER=process.env.CREATOR_OWNER||'demo2rlogicssolutions';
const APP=process.env.CREATOR_APP||'loan-management-backend-system';
const API=process.env.CREATOR_API_BASE||'https://www.zohoapis.eu/creator/v2.1';
const ACCOUNTS=process.env.ZOHO_ACCOUNTS_URL||'https://accounts.zoho.eu';
const APPLICATION_REPORT=process.env.CREATOR_LOAN_APPLICATION_REPORT||'loan_application_Report';
const MASTER_REPORT=process.env.CREATOR_LOAN_MASTER_REPORT||'loan_master_Report';
const EMI_FORM=process.env.CREATOR_EMI_SCHEDULE_FORM||'emi_schedule';
const EMI_REPORT=process.env.CREATOR_EMI_SCHEDULE_REPORT||'emi_schedule_Report';
const PAYMENT_FORM=process.env.CREATOR_LOAN_PAYMENT_FORM||'loan_payment';
const PAYMENT_REPORT=process.env.CREATOR_LOAN_PAYMENT_REPORT||'loan_payment_Report';
const RAZORPAY_API='https://api.razorpay.com/v1';
let cache={value:null,expiresAt:0};
const hash=t=>crypto.createHash('sha256').update(t).digest('hex');
const safe=v=>String(v).replace(/'/g,"''");
const z=req=>catalyst.initialize(req);
async function query(req,q){return(await z(req).zcql().executeZCQLQuery(q))||[]}
async function token(){if(cache.value&&Date.now()<cache.expiresAt)return cache.value;const body=new URLSearchParams({refresh_token:process.env.ZOHO_REFRESH_TOKEN,client_id:process.env.ZOHO_CLIENT_ID,client_secret:process.env.ZOHO_CLIENT_SECRET,grant_type:'refresh_token'});const r=await fetch(`${ACCOUNTS}/oauth/v2/token`,{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:body.toString()});const d=await r.json().catch(()=>({}));if(!r.ok||!d.access_token)throw Object.assign(new Error('Unable to connect to Zoho Creator.'),{statusCode:502,oauth:{httpStatus:r.status,error:d.error||'token_exchange_failed'}});cache={value:d.access_token,expiresAt:Date.now()+45*60*1000};return cache.value}
async function user(req){const s=req.cookies?.[COOKIE];if(!s)return null;const rows=await query(req,`SELECT * FROM ${SESSIONS} WHERE TOKEN_HASH='${safe(hash(s))}'`);if(!rows.length)return null;const session=rows[0][SESSIONS]||rows[0];if(session.REVOKED||new Date(session.EXPIRES_AT)<=new Date())return null;const users=await query(req,`SELECT PORTAL_USER_ID,EMAIL,CREATOR_CUSTOMER_ID,ACCOUNT_STATUS FROM ${USERS} WHERE PORTAL_USER_ID='${safe(session.PORTAL_USER_ID)}'`);const u=users[0]?.[USERS]||users[0];return u?.ACCOUNT_STATUS==='ACTIVE'&&u.CREATOR_CUSTOMER_ID?u:null}
function id(v){if(v==null)return'';if(typeof v==='object')return String(v.ID||v.id||v.value||v.zc_display_value||'');return String(v)}
function text(v){if(v==null)return'';if(typeof v==='object')return String(v.zc_display_value||v.display_value||v.name||v.value||v.ID||'');return String(v)}
function match(v,target){if(v==null)return false;if(Array.isArray(v))return v.some(x=>match(x,target));if(typeof v==='object')return[v.ID,v.id,v.value,v.zc_display_value].some(x=>String(x||'')===String(target));return String(v)===String(target)}
async function report(name){const t=await token();const r=await fetch(`${API}/data/${OWNER}/${APP}/report/${name}`,{headers:{Authorization:`Zoho-oauthtoken ${t}`}});const d=await r.json().catch(()=>({}));if(!r.ok||(!Array.isArray(d.data)&&d.code!==3000))throw Object.assign(new Error(`Unable to load ${name}.`),{statusCode:502,creator:d});return d.data||[]}
async function create(form,data){const t=await token();const r=await fetch(`${API}/data/${OWNER}/${APP}/form/${form}`,{method:'POST',headers:{Authorization:`Zoho-oauthtoken ${t}`,'Content-Type':'application/json'},body:JSON.stringify({data,result:{message:true}})});const d=await r.json().catch(()=>({}));const recordId=d?.data?.ID||(Array.isArray(d.result)?d.result[0]?.data?.ID:null);if(!r.ok||!recordId)throw Object.assign(new Error(`Creator rejected ${form}.`),{statusCode:502,creator:d});return String(recordId)}
async function patch(reportName,recordId,data){const t=await token();const r=await fetch(`${API}/data/${OWNER}/${APP}/report/${reportName}/${recordId}`,{method:'PATCH',headers:{Authorization:`Zoho-oauthtoken ${t}`,'Content-Type':'application/json'},body:JSON.stringify({data,result:{message:true}})});const d=await r.json().catch(()=>({}));if(!r.ok||!(d.code===3000||d.data||Array.isArray(d.result)))throw Object.assign(new Error(`Unable to update ${reportName}.`),{statusCode:502,creator:d});return d}
function parseDate(v){if(!v)return new Date();const raw=String(v);const m=raw.match(/^(\d{2})-([A-Za-z]{3})-(\d{4})/);if(m){const months={Jan:0,Feb:1,Mar:2,Apr:3,May:4,Jun:5,Jul:6,Aug:7,Sep:8,Oct:9,Nov:10,Dec:11};return new Date(Number(m[3]),months[m[2]],Number(m[1]))}const d=new Date(raw);return Number.isNaN(d.getTime())?new Date():d}
function creatorDate(d){const months=['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];return`${String(d.getDate()).padStart(2,'0')}-${months[d.getMonth()]}-${d.getFullYear()} ${String(d.getHours()).padStart(2,'0')}:${String(d.getMinutes()).padStart(2,'0')}:${String(d.getSeconds()).padStart(2,'0')}`}
function emiPayment(p,annual,n){p=Number(p||0);n=Math.max(1,Number(n||1));const r=Number(annual||0)/1200;if(!r)return Number((p/n).toFixed(2));const x=Math.pow(1+r,n);return Number((p*r*x/(x-1)).toFixed(2))}
function scheduleFor(master){const principal=Number(master.principal_amount||0),rate=Number(master.interest_rate||0),tenure=Math.max(1,Number(master.tenure||1)),payment=Number(master.emi_amount||0)||emiPayment(principal,rate,tenure),monthlyRate=rate/1200,start=parseDate(master.disbursement_date),rows=[];let opening=principal;for(let i=1;i<=tenure;i++){const interest=Number((opening*monthlyRate).toFixed(2));let principalPart=Number((payment-interest).toFixed(2));if(i===tenure||principalPart>opening)principalPart=Number(opening.toFixed(2));const actualPayment=Number((principalPart+interest).toFixed(2));const closing=Number(Math.max(0,opening-principalPart).toFixed(2));const due=new Date(start);due.setMonth(due.getMonth()+i);rows.push({emiNumber:i,dueDate:creatorDate(due),emiAmount:actualPayment,openingPrincipal:Number(opening.toFixed(2)),principalComponent:principalPart,interestComponent:interest,closingPrincipal:closing});opening=closing}return rows}
function mapEmi(r){return{id:id(r.ID),emiNumber:Number(r.emi_number||0),dueDate:text(r.due_date),emiAmount:Number(r.emi_amount||0),openingPrincipal:Number(r.opening_principal||0),principalComponent:Number(r.principal_component||0),interestComponent:Number(r.interest_component||0),closingPrincipal:Number(r.closing_principal||0),paymentDate:text(r.payment_date),paymentReference:text(r.payment_reference),paymentStatus:text(r.payment_status)||'Pending'}}
function mapPayment(r){return{id:id(r.ID),emiId:id(r.emi),amount:Number(r.payment_amount||0),date:text(r.payment_date),gateway:text(r.payment_gateway),mode:text(r.payment_mode),status:text(r.payment_status),orderId:text(r.payment_gateway_order_id),gatewayPaymentId:text(r.payment_gateway_payment_id),transactionReference:text(r.transaction_reference),remarks:text(r.payment_remarks)}}
async function ensureSchedule(u,master,existing){const appId=id(master.loan_application);const mine=existing.filter(r=>match(r.customer,u.CREATOR_CUSTOMER_ID)&&match(r.loan_application,appId));if(mine.length)return mine;for(const row of scheduleFor(master)){await create(EMI_FORM,{customer:String(u.CREATOR_CUSTOMER_ID),loan_application:appId,emi_number:row.emiNumber,due_date:row.dueDate,emi_amount:row.emiAmount,opening_principal:row.openingPrincipal,principal_component:row.principalComponent,interest_component:row.interestComponent,closing_principal:row.closingPrincipal,payment_status:'Pending'})}return(await report(EMI_REPORT)).filter(r=>match(r.customer,u.CREATOR_CUSTOMER_ID)&&match(r.loan_application,appId))}
function razorpayConfigured(){return Boolean(process.env.RAZORPAY_KEY_ID&&process.env.RAZORPAY_KEY_SECRET)}
async function razorpay(path,options={}){if(!razorpayConfigured())throw Object.assign(new Error('Razorpay is not configured.'),{statusCode:503});const auth=Buffer.from(`${process.env.RAZORPAY_KEY_ID}:${process.env.RAZORPAY_KEY_SECRET}`).toString('base64');const r=await fetch(`${RAZORPAY_API}${path}`,{...options,headers:{Authorization:`Basic ${auth}`,'Content-Type':'application/json',...(options.headers||{})}});const d=await r.json().catch(()=>({}));if(!r.ok)throw Object.assign(new Error(d?.error?.description||'Razorpay request failed.'),{statusCode:502,razorpay:{httpStatus:r.status,error:d?.error||d}});return d}
async function refreshMasterForPayment(u,appId,master){const refreshed=await report(EMI_REPORT);const mine=refreshed.filter(r=>match(r.customer,u.CREATOR_CUSTOMER_ID)&&match(r.loan_application,appId)).sort((a,b)=>Number(a.emi_number||0)-Number(b.emi_number||0));const paid=mine.filter(r=>String(text(r.payment_status)).toLowerCase()==='paid');const pending=mine.filter(r=>String(text(r.payment_status)).toLowerCase()!=='paid');const totalPaid=paid.reduce((s,r)=>s+Number(r.emi_amount||0),0);const outstanding=pending.length?Number(pending[0].opening_principal||0):0;await patch(MASTER_REPORT,id(master.ID),{number_of_emis_paid:paid.length,number_of_emis_pending:pending.length,total_paid_amount:Number(totalPaid.toFixed(2)),outstanding_principal:Number(outstanding.toFixed(2)),next_emi_date:pending[0]?text(pending[0].due_date):'',loan_status:pending.length?'Active':'Closed'});return{paid:paid.length,pending:pending.length,totalPaid,outstanding}}
router.get('/dashboard',async(req,res)=>{const requestId=`DASH-${crypto.randomUUID()}`;try{const u=await user(req);if(!u)return res.status(401).json({message:'Please sign in again.'});const[apps,masters,emis]=await Promise.all([report(APPLICATION_REPORT),report(MASTER_REPORT),report(EMI_REPORT)]);const myApps=apps.filter(r=>match(r.customer,u.CREATOR_CUSTOMER_ID));const myMasters=masters.filter(r=>match(r.customer,u.CREATOR_CUSTOMER_ID));const myEmis=emis.filter(r=>match(r.customer,u.CREATOR_CUSTOMER_ID));const paidEmis=myEmis.filter(r=>String(text(r.payment_status)).toLowerCase()==='paid');const pendingEmis=myEmis.filter(r=>String(text(r.payment_status)).toLowerCase()!=='paid');const pending=pendingEmis.slice().sort((a,b)=>parseDate(a.due_date)-parseDate(b.due_date));const totalScheduled=myEmis.reduce((s,r)=>s+Number(r.emi_amount||0),0);const totalPaid=paidEmis.reduce((s,r)=>s+Number(r.emi_amount||0),0);const paymentProgress=totalScheduled>0?Math.min(100,Math.round(totalPaid/totalScheduled*100)):0;res.json({stats:{applications:myApps.length,activeLoans:myMasters.filter(r=>String(text(r.loan_status)).toLowerCase()==='active').length,nextEmi:pending[0]?{amount:Number(pending[0].emi_amount||0),dueDate:text(pending[0].due_date)}:null,outstandingPrincipal:myMasters.reduce((s,r)=>s+Number(r.outstanding_principal||0),0),paymentProgress,paidEmis:paidEmis.length,pendingEmis:pendingEmis.length,totalScheduled:Number(totalScheduled.toFixed(2)),totalPaid:Number(totalPaid.toFixed(2))},recentApplications:myApps.slice().sort((a,b)=>parseDate(b.applied_date)-parseDate(a.applied_date)).slice(0,4).map(r=>({id:id(r.ID),applicationId:text(r.application_id)||id(r.ID),loanType:text(r.loan_type),amount:Number(r.requested_amount||0),status:text(r.application_status)||'Submitted',appliedDate:text(r.applied_date)}))})}catch(e){console.error('[DASHBOARD_FAILED]',JSON.stringify({requestId,message:e.message,oauth:e.oauth||null,creator:e.creator||null}));res.status(e.statusCode||500).json({message:'Unable to load dashboard.',requestId})}});
router.get('/payments',async(req,res)=>{const requestId=`PAY-${crypto.randomUUID()}`;try{const u=await user(req);if(!u)return res.status(401).json({message:'Please sign in again.'});const[masters,allEmis,payments]=await Promise.all([report(MASTER_REPORT),report(EMI_REPORT),report(PAYMENT_REPORT)]);const myMasters=masters.filter(r=>match(r.customer,u.CREATOR_CUSTOMER_ID));let schedule=allEmis;for(const master of myMasters.filter(r=>String(text(r.loan_status)).toLowerCase()==='active'))schedule=schedule.concat(await ensureSchedule(u,master,schedule));const seen=new Set();const myEmis=schedule.filter(r=>match(r.customer,u.CREATOR_CUSTOMER_ID)).filter(r=>{const k=id(r.ID);if(seen.has(k))return false;seen.add(k);return true}).map(mapEmi).sort((a,b)=>a.emiNumber-b.emiNumber);const myPayments=payments.filter(r=>match(r.customer,u.CREATOR_CUSTOMER_ID)).map(mapPayment);const next=myEmis.find(x=>String(x.paymentStatus).toLowerCase()!=='paid')||null;res.json({gateway:{provider:'Razorpay',configured:razorpayConfigured(),mode:process.env.RAZORPAY_MODE||'test'},customer:{email:u.EMAIL},loan:myMasters[0]?{id:id(myMasters[0].ID),principalAmount:Number(myMasters[0].principal_amount||0),emiAmount:Number(myMasters[0].emi_amount||0),interestRate:Number(myMasters[0].interest_rate||0),tenure:Number(myMasters[0].tenure||0),loanStatus:text(myMasters[0].loan_status),outstandingPrincipal:Number(myMasters[0].outstanding_principal||0),totalPaidAmount:Number(myMasters[0].total_paid_amount||0)}:null,schedule:myEmis,payments:myPayments,nextEmi:next})}catch(e){console.error('[PAYMENTS_LOAD_FAILED]',JSON.stringify({requestId,message:e.message,oauth:e.oauth||null,creator:e.creator||null}));res.status(e.statusCode||500).json({message:'Unable to load repayment details.',requestId})}});
router.post('/payments/:emiId/create-order',async(req,res)=>{const requestId=`ORDER-${crypto.randomUUID()}`;try{const u=await user(req);if(!u)return res.status(401).json({message:'Please sign in again.'});if(!razorpayConfigured())return res.status(503).json({message:'Online payment gateway is not configured yet.',requestId});const[emis,masters,payments]=await Promise.all([report(EMI_REPORT),report(MASTER_REPORT),report(PAYMENT_REPORT)]);const row=emis.find(r=>id(r.ID)===String(req.params.emiId)&&match(r.customer,u.CREATOR_CUSTOMER_ID));if(!row)return res.status(404).json({message:'EMI not found.'});if(String(text(row.payment_status)).toLowerCase()==='paid')return res.status(409).json({message:'This EMI is already paid.'});const existing=payments.find(r=>match(r.customer,u.CREATOR_CUSTOMER_ID)&&match(r.emi,id(row.ID))&&['created','pending'].includes(String(text(r.payment_status)).toLowerCase()));const appId=id(row.loan_application),master=masters.find(r=>match(r.customer,u.CREATOR_CUSTOMER_ID)&&match(r.loan_application,appId)&&String(text(r.loan_status)).toLowerCase()==='active');if(!master)return res.status(400).json({message:'Active loan account not found.'});if(existing&&text(existing.payment_gateway_order_id))return res.json({keyId:process.env.RAZORPAY_KEY_ID,orderId:text(existing.payment_gateway_order_id),amount:Math.round(Number(row.emi_amount||0)*100),currency:'INR',emi:{id:id(row.ID),number:Number(row.emi_number||0),amount:Number(row.emi_amount||0),dueDate:text(row.due_date)},customer:{email:u.EMAIL}});const amount=Math.round(Number(row.emi_amount||0)*100);if(amount<100)return res.status(400).json({message:'EMI amount is too small for online payment.'});const order=await razorpay('/orders',{method:'POST',body:JSON.stringify({amount,currency:'INR',receipt:`emi_${id(row.ID).slice(-18)}_${Date.now()}`,notes:{emi_id:id(row.ID),loan_application:appId,customer_id:String(u.CREATOR_CUSTOMER_ID)}})});await create(PAYMENT_FORM,{customer:String(u.CREATOR_CUSTOMER_ID),loan_application:appId,emi:id(row.ID),payment_amount:Number(row.emi_amount||0),payment_gateway:'Razorpay',payment_gateway_order_id:order.id,payment_mode:'Online',payment_remarks:'Razorpay order created. Awaiting verified payment.',payment_status:'Created'});res.json({keyId:process.env.RAZORPAY_KEY_ID,orderId:order.id,amount:order.amount,currency:order.currency||'INR',emi:{id:id(row.ID),number:Number(row.emi_number||0),amount:Number(row.emi_amount||0),dueDate:text(row.due_date)},customer:{email:u.EMAIL}})}catch(e){console.error('[RAZORPAY_ORDER_FAILED]',JSON.stringify({requestId,message:e.message,razorpay:e.razorpay||null,creator:e.creator||null}));res.status(e.statusCode||500).json({message:e.message||'Unable to start online payment.',requestId})}});
router.post('/payments/:emiId/verify',async(req,res)=>{const requestId=`VERIFY-${crypto.randomUUID()}`;try{const u=await user(req);if(!u)return res.status(401).json({message:'Please sign in again.'});const orderId=String(req.body.razorpay_order_id||''),paymentId=String(req.body.razorpay_payment_id||''),signature=String(req.body.razorpay_signature||'');if(!orderId||!paymentId||!signature)return res.status(400).json({message:'Incomplete payment verification details.'});const[emis,masters,payments]=await Promise.all([report(EMI_REPORT),report(MASTER_REPORT),report(PAYMENT_REPORT)]);const row=emis.find(r=>id(r.ID)===String(req.params.emiId)&&match(r.customer,u.CREATOR_CUSTOMER_ID));if(!row)return res.status(404).json({message:'EMI not found.'});if(String(text(row.payment_status)).toLowerCase()==='paid')return res.json({ok:true,alreadyPaid:true});const pendingPayment=payments.find(r=>match(r.customer,u.CREATOR_CUSTOMER_ID)&&match(r.emi,id(row.ID))&&text(r.payment_gateway_order_id)===orderId);if(!pendingPayment)return res.status(400).json({message:'Payment order does not match this EMI.'});const expected=crypto.createHmac('sha256',process.env.RAZORPAY_KEY_SECRET).update(`${orderId}|${paymentId}`).digest('hex');const valid=expected.length===signature.length&&crypto.timingSafeEqual(Buffer.from(expected),Buffer.from(signature));if(!valid)return res.status(400).json({message:'Payment verification failed.'});const remote=await razorpay(`/payments/${encodeURIComponent(paymentId)}`);const expectedAmount=Math.round(Number(row.emi_amount||0)*100);if(remote.order_id!==orderId||Number(remote.amount)!==expectedAmount||String(remote.currency).toUpperCase()!=='INR')return res.status(400).json({message:'Payment details do not match the EMI.'});if(remote.status!=='captured'&&!remote.captured)return res.status(409).json({message:'Payment is authorised but not captured yet. Please retry after capture.'});const now=new Date(),txn=paymentId;await patch(PAYMENT_REPORT,id(pendingPayment.ID),{payment_date:creatorDate(now),payment_gateway_payment_id:paymentId,payment_mode:remote.method?`Online - ${remote.method}`:'Online',payment_remarks:'Razorpay payment verified server-side and confirmed captured.',payment_status:'Success',transaction_reference:txn});await patch(EMI_REPORT,id(row.ID),{payment_status:'Paid',payment_date:creatorDate(now),payment_reference:txn});const appId=id(row.loan_application),master=masters.find(r=>match(r.customer,u.CREATOR_CUSTOMER_ID)&&match(r.loan_application,appId));if(master)await refreshMasterForPayment(u,appId,master);res.json({ok:true,paymentId,transactionReference:txn})}catch(e){console.error('[RAZORPAY_VERIFY_FAILED]',JSON.stringify({requestId,message:e.message,razorpay:e.razorpay||null,creator:e.creator||null}));res.status(e.statusCode||500).json({message:e.message||'Unable to verify online payment.',requestId})}});
router.post('/payments/:emiId/demo-pay',async(req,res)=>{const requestId=`PAYMENT-${crypto.randomUUID()}`;try{const u=await user(req);if(!u)return res.status(401).json({message:'Please sign in again.'});const[emis,masters]=await Promise.all([report(EMI_REPORT),report(MASTER_REPORT)]);const row=emis.find(r=>id(r.ID)===String(req.params.emiId)&&match(r.customer,u.CREATOR_CUSTOMER_ID));if(!row)return res.status(404).json({message:'EMI not found.'});if(String(text(row.payment_status)).toLowerCase()==='paid')return res.status(409).json({message:'This EMI is already paid.'});const appId=id(row.loan_application),master=masters.find(r=>match(r.customer,u.CREATOR_CUSTOMER_ID)&&match(r.loan_application,appId));if(!master)return res.status(400).json({message:'Active loan account not found.'});const now=new Date(),stamp=Date.now(),txn=`DEMO-TXN-${stamp}`,paymentId=await create(PAYMENT_FORM,{customer:String(u.CREATOR_CUSTOMER_ID),loan_application:appId,emi:id(row.ID),payment_amount:Number(row.emi_amount||0),payment_date:creatorDate(now),payment_gateway:'Demo Gateway',payment_gateway_order_id:`DEMO-ORDER-${stamp}`,payment_gateway_payment_id:`DEMO-PAY-${stamp}`,payment_mode:'Online - Demo',payment_remarks:'PoC simulated payment. No real money was transferred.',payment_status:'Success',transaction_reference:txn});await patch(EMI_REPORT,id(row.ID),{payment_status:'Paid',payment_date:creatorDate(now),payment_reference:txn});await refreshMasterForPayment(u,appId,master);res.json({ok:true,paymentId,transactionReference:txn})}catch(e){console.error('[DEMO_PAYMENT_FAILED]',JSON.stringify({requestId,message:e.message,oauth:e.oauth||null,creator:e.creator||null}));res.status(e.statusCode||500).json({message:'Unable to complete demo payment.',requestId})}});
module.exports=router;
