const express=require('express');const cookieParser=require('cookie-parser');const crypto=require('crypto');const bcrypt=require('bcryptjs');const catalyst=require('zcatalyst-sdk-node');
const app=express();app.use(express.json());app.use(cookieParser());
const USERS='Portal_Users',SESSIONS='Portal_Sessions',COOKIE='lms_session',TTL=12*60*60*1000;
const now=()=>new Date();const fmt=d=>d.toISOString().slice(0,19).replace('T',' ');const hash=t=>crypto.createHash('sha256').update(t).digest('hex');const id=p=>`${p}-${crypto.randomUUID()}`;
function z(req){return catalyst.initialize(req)}
async function query(req,q){const r=await z(req).zcql().executeZCQLQuery(q);return r||[]}
function safe(v){return String(v).replace(/'/g,"''")}
app.get('/health',(req,res)=>res.json({ok:true,service:'customer_auth_api'}));
app.post('/api/auth/register',async(req,res)=>{try{const email=String(req.body.email||'').trim().toLowerCase(),password=String(req.body.password||'');if(!/^\S+@\S+\.\S+$/.test(email))return res.status(400).json({message:'Enter a valid email address.'});if(password.length<10)return res.status(400).json({message:'Password must contain at least 10 characters.'});if(!req.body.privacyConsent)return res.status(400).json({message:'Privacy consent is required.'});const found=await query(req,`SELECT ROWID FROM ${USERS} WHERE EMAIL='${safe(email)}'`);if(found.length)return res.status(409).json({message:'An account already exists for this email.'});const t=now(),portalId=id('PU');await z(req).datastore().table(USERS).insertRow({PORTAL_USER_ID:portalId,EMAIL:email,PASSWORD_HASH:await bcrypt.hash(password,12),ACCOUNT_STATUS:'ACTIVE',EMAIL_VERIFIED:false,FAILED_LOGIN_ATTEMPTS:0,CREATED_AT:fmt(t),UPDATED_AT:fmt(t)});return res.status(201).json({ok:true,portalUserId:portalId});}catch(e){console.error(e);res.status(500).json({message:'Unable to create account.'})}});
app.post('/api/auth/login',async(req,res)=>{try{const email=String(req.body.email||'').trim().toLowerCase(),password=String(req.body.password||'');const rows=await query(req,`SELECT * FROM ${USERS} WHERE EMAIL='${safe(email)}'`);if(!rows.length)return res.status(401).json({message:'Invalid email or password.'});const u=rows[0][USERS]||rows[0];if(u.ACCOUNT_STATUS!=='ACTIVE'||!(await bcrypt.compare(password,u.PASSWORD_HASH)))return res.status(401).json({message:'Invalid email or password.'});const token=crypto.randomBytes(48).toString('base64url'),expires=new Date(Date.now()+TTL);await z(req).datastore().table(SESSIONS).insertRow({SESSION_ID:id('SES'),PORTAL_USER_ID:u.PORTAL_USER_ID,TOKEN_HASH:hash(token),EXPIRES_AT:fmt(expires),REVOKED:false,CREATED_AT:fmt(now())});res.cookie(COOKIE,token,{httpOnly:true,sameSite:'lax',secure:true,maxAge:TTL,path:'/'});res.json({ok:true,user:{portalUserId:u.PORTAL_USER_ID,email:u.EMAIL,creatorCustomerId:u.CREATOR_CUSTOMER_ID||null}});}catch(e){console.error(e);res.status(500).json({message:'Unable to sign in.'})}});
app.get('/api/auth/me',async(req,res)=>{try{const token=req.cookies[COOKIE];if(!token)return res.status(401).json({message:'Authentication required.'});const sessions=await query(req,`SELECT * FROM ${SESSIONS} WHERE TOKEN_HASH='${safe(hash(token))}'`);if(!sessions.length)return res.status(401).json({message:'Session expired.'});const s=sessions[0][SESSIONS]||sessions[0];if(s.REVOKED||new Date(s.EXPIRES_AT)<=now())return res.status(401).json({message:'Session expired.'});const users=await query(req,`SELECT PORTAL_USER_ID,EMAIL,CREATOR_CUSTOMER_ID,ACCOUNT_STATUS FROM ${USERS} WHERE PORTAL_USER_ID='${safe(s.PORTAL_USER_ID)}'`);if(!users.length)return res.status(401).json({message:'Authentication required.'});const u=users[0][USERS]||users[0];res.json({user:{portalUserId:u.PORTAL_USER_ID,email:u.EMAIL,creatorCustomerId:u.CREATOR_CUSTOMER_ID||null}});}catch(e){console.error(e);res.status(500).json({message:'Unable to validate session.'})}});
app.post('/api/auth/logout',async(req,res)=>{try{const token=req.cookies[COOKIE];if(token){const sessions=await query(req,`SELECT ROWID FROM ${SESSIONS} WHERE TOKEN_HASH='${safe(hash(token))}'`);for(const r of sessions){const s=r[SESSIONS]||r;if(s.ROWID)await z(req).datastore().table(SESSIONS).updateRow({ROWID:s.ROWID,REVOKED:true})}}res.clearCookie(COOKIE,{path:'/'});res.json({ok:true});}catch(e){console.error(e);res.clearCookie(COOKIE,{path:'/'});res.json({ok:true})}});
module.exports=app;
