const express=require('express');
const cookieParser=require('cookie-parser');
const crypto=require('crypto');
const bcrypt=require('bcryptjs');
const catalyst=require('zcatalyst-sdk-node');
const applicationRoutes=require('./applicationRoutes');
const documentRoutes=require('./documentRoutes');
const profileRoutes=require('./profileRoutes');
const approvalSyncRoutes=require('./approvalSyncRoutes');
const disbursementRoutes=require('./disbursementRoutes');
const financeRoutes=require('./financeRoutes');
const app=express();
const USERS='Portal_Users',SESSIONS='Portal_Sessions',COOKIE='lms_session',TTL=12*60*60*1000;
const CREATOR_OWNER=process.env.CREATOR_OWNER||'demo2rlogicssolutions',CREATOR_APP=process.env.CREATOR_APP||'loan-management-backend-system',CREATOR_CUSTOMER_FORM=process.env.CREATOR_CUSTOMER_FORM||'customer_profile',CREATOR_API_BASE=process.env.CREATOR_API_BASE||'https://www.zohoapis.eu/creator/v2.1',ZOHO_ACCOUNTS_URL=process.env.ZOHO_ACCOUNTS_URL||'https://accounts.zoho.eu';
app.use(express.json({limit:'14mb'}));app.use(cookieParser());
const now=()=>new Date(),fmt=d=>d.toISOString().slice(0,19).replace('T',' '),hash=t=>crypto.createHash('sha256').update(t).digest('hex'),id=p=>`${p}-${crypto.randomUUID()}`;function z(req){return catalyst.initialize(req)}async function query(req,q){return(await z(req).zcql().executeZCQLQuery(q))||[]}function safe(v){return String(v).replace(/'/g,"''")}function normalizeIndianMobile(value){let mobile=String(value||'').trim().replace(/[\s-]/g,'');if(mobile.startsWith('+91'))mobile=mobile.slice(3);else if(mobile.startsWith('91')&&mobile.length===12)mobile=mobile.slice(2);return mobile}function creatorDateTime(v){if(!v)return null;const d=new Date(`${v}T00:00:00Z`);if(Number.isNaN(d.getTime()))return null;const m=['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];return`${String(d.getUTCDate()).padStart(2,'0')}-${m[d.getUTCMonth()]}-${d.getUTCFullYear()} 00:00:00`}function creatorName(v){const p=String(v||'').trim().split(/\s+/).filter(Boolean);return p.length<2?{}:{first_name:p[0],last_name:p.slice(1).join(' ')}}
function requireCreatorOAuthConfig(){const missing=['ZOHO_CLIENT_ID','ZOHO_CLIENT_SECRET','ZOHO_REFRESH_TOKEN'].filter(k=>!process.env[k]);if(missing.length)throw Object.assign(new Error('Creator OAuth is not configured.'),{statusCode:503})}async function getCreatorAccessToken(){requireCreatorOAuthConfig();const params=new URLSearchParams({refresh_token:process.env.ZOHO_REFRESH_TOKEN,client_id:process.env.ZOHO_CLIENT_ID,client_secret:process.env.ZOHO_CLIENT_SECRET,grant_type:'refresh_token'}),r=await fetch(`${ZOHO_ACCOUNTS_URL}/oauth/v2/token`,{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:params.toString()}),d=await r.json().catch(()=>({}));if(!r.ok||!d.access_token)throw Object.assign(new Error('Unable to obtain Zoho access token.'),{statusCode:502,creatorResponse:d});return d.access_token}
async function createCreatorCustomer(c){const token=await getCreatorAccessToken(),url=`${CREATOR_API_BASE}/data/${CREATOR_OWNER}/${CREATOR_APP}/form/${CREATOR_CUSTOMER_FORM}`,address={address_line_1:c.address};if(c.addressLine2)address.address_line_2=c.addressLine2;if(c.city)address.district_city=c.city;if(c.state)address.state_province=c.state;if(c.postalCode)address.postal_Code=c.postalCode;if(c.country)address.country=c.country;const data={customer_name:creatorName(c.customerName),email:c.email,mobile_number:c.mobileNumber,date_of_birth:creatorDateTime(c.dateOfBirth),address,employment_type:c.employmentType,annual_income:Number(c.annualIncome),portal_user_id:c.portalUserId,portal_account_status1:'Active',privacy_consent_accepted1:true,customer_status:'Active'};if(c.employerName)data.employer_name=c.employerName;if(c.officialEmail)data.official_email=c.officialEmail;if(c.workExperience!==''&&c.workExperience!=null)data.work_experience=Number(c.workExperience);const r=await fetch(url,{method:'POST',headers:{Authorization:`Zoho-oauthtoken ${token}`,'Content-Type':'application/json'},body:JSON.stringify({data,result:{message:true}})}),d=await r.json().catch(()=>({})),first=Array.isArray(d.result)?d.result[0]:null,creatorId=d?.data?.ID||first?.data?.ID;if(!r.ok||!creatorId)throw Object.assign(new Error(first?.message||d?.message||'Unable to create customer in Zoho Creator.'),{statusCode:502,creatorResponse:d});return String(creatorId)}
app.get('/health',(req,res)=>res.json({ok:true,service:'customer_auth_api',creatorIntegration:Boolean(process.env.ZOHO_CLIENT_ID&&process.env.ZOHO_CLIENT_SECRET&&process.env.ZOHO_REFRESH_TOKEN)}));
app.post('/api/auth/register',async(req,res)=>{try{const email=String(req.body.email||'').trim().toLowerCase(),password=String(req.body.password||''),customerName=String(req.body.customerName||'').trim().replace(/\s+/g,' '),mobileNumber=normalizeIndianMobile(req.body.mobileNumber),dateOfBirth=String(req.body.dateOfBirth||'').trim(),address=String(req.body.address||'').trim(),addressLine2=String(req.body.addressLine2||'').trim(),city=String(req.body.city||'').trim(),state=String(req.body.state||'').trim(),postalCode=String(req.body.postalCode||'').trim(),country=String(req.body.country||'').trim(),employmentType=String(req.body.employmentType||'').trim(),annualIncome=Number(req.body.annualIncome),employerName=String(req.body.employerName||'').trim(),officialEmail=String(req.body.officialEmail||'').trim().toLowerCase(),workExperience=req.body.workExperience;if(customerName.split(/\s+/).filter(Boolean).length<2)return res.status(400).json({field:'customerName',message:'Enter your first and last name.'});if(!/^\S+@\S+\.\S+$/.test(email))return res.status(400).json({field:'email',message:'Enter a valid email address.'});if(!/^[6-9][0-9]{9}$/.test(mobileNumber))return res.status(400).json({field:'mobileNumber',message:'Enter a valid 10-digit Indian mobile number.'});if(!dateOfBirth||!creatorDateTime(dateOfBirth)||!address||!city||!employmentType||!Number.isFinite(annualIncome)||annualIncome<=0)return res.status(400).json({message:'Complete all required profile fields.'});if(password.length<10)return res.status(400).json({field:'password',message:'Password must contain at least 10 characters.'});if(!req.body.privacyConsent)return res.status(400).json({field:'privacyConsent',message:'Privacy consent is required.'});if((await query(req,`SELECT ROWID FROM ${USERS} WHERE EMAIL='${safe(email)}'`)).length)return res.status(409).json({field:'email',message:'An account already exists with this email address.'});const t=now(),portalId=id('PU'),creatorCustomerId=await createCreatorCustomer({portalUserId:portalId,customerName,email,mobileNumber,dateOfBirth,address,addressLine2,city,state,postalCode,country,employmentType,annualIncome,employerName,officialEmail,workExperience});await z(req).datastore().table(USERS).insertRow({PORTAL_USER_ID:portalId,EMAIL:email,PASSWORD_HASH:await bcrypt.hash(password,12),ACCOUNT_STATUS:'ACTIVE',EMAIL_VERIFIED:false,CREATOR_CUSTOMER_ID:creatorCustomerId,FAILED_LOGIN_ATTEMPTS:0,CREATED_AT:fmt(t),UPDATED_AT:fmt(t)});res.status(201).json({ok:true,portalUserId:portalId,creatorCustomerId})}catch(e){const requestId=id('REG');console.error('[REGISTER_FAILED]',requestId,e);res.status(e.statusCode||500).json({message:'Unable to create account.',requestId})}});
app.post('/api/auth/login',async(req,res)=>{try{const email=String(req.body.email||'').trim().toLowerCase(),password=String(req.body.password||''),rows=await query(req,`SELECT * FROM ${USERS} WHERE EMAIL='${safe(email)}'`);if(!rows.length)return res.status(401).json({message:'Invalid email or password.'});const u=rows[0][USERS]||rows[0];if(u.ACCOUNT_STATUS!=='ACTIVE'||!(await bcrypt.compare(password,u.PASSWORD_HASH)))return res.status(401).json({message:'Invalid email or password.'});const token=crypto.randomBytes(48).toString('base64url'),expires=new Date(Date.now()+TTL);await z(req).datastore().table(SESSIONS).insertRow({SESSION_ID:id('SES'),PORTAL_USER_ID:u.PORTAL_USER_ID,TOKEN_HASH:hash(token),EXPIRES_AT:fmt(expires),REVOKED:false,CREATED_AT:fmt(now())});res.cookie(COOKIE,token,{httpOnly:true,sameSite:'lax',secure:true,maxAge:TTL,path:'/'});res.json({ok:true,user:{portalUserId:u.PORTAL_USER_ID,email:u.EMAIL,creatorCustomerId:u.CREATOR_CUSTOMER_ID||null}})}catch(e){console.error(e);res.status(500).json({message:'Unable to sign in.'})}});
app.get('/api/auth/me',async(req,res)=>{try{const token=req.cookies[COOKIE];if(!token)return res.status(401).json({message:'Authentication required.'});const rows=await query(req,`SELECT * FROM ${SESSIONS} WHERE TOKEN_HASH='${safe(hash(token))}'`);if(!rows.length)return res.status(401).json({message:'Session expired.'});const s=rows[0][SESSIONS]||rows[0];if(s.REVOKED||new Date(s.EXPIRES_AT)<=now())return res.status(401).json({message:'Session expired.'});const users=await query(req,`SELECT PORTAL_USER_ID,EMAIL,CREATOR_CUSTOMER_ID,ACCOUNT_STATUS FROM ${USERS} WHERE PORTAL_USER_ID='${safe(s.PORTAL_USER_ID)}'`),u=users[0]?.[USERS]||users[0];if(!u)return res.status(401).json({message:'Authentication required.'});res.json({user:{portalUserId:u.PORTAL_USER_ID,email:u.EMAIL,creatorCustomerId:u.CREATOR_CUSTOMER_ID||null}})}catch(e){res.status(500).json({message:'Unable to validate session.'})}});
app.post('/api/auth/logout',async(req,res)=>{try{const token=req.cookies[COOKIE];if(token){const rows=await query(req,`SELECT ROWID FROM ${SESSIONS} WHERE TOKEN_HASH='${safe(hash(token))}'`);for(const r of rows){const s=r[SESSIONS]||r;if(s.ROWID)await z(req).datastore().table(SESSIONS).updateRow({ROWID:s.ROWID,REVOKED:true})}}res.clearCookie(COOKIE,{path:'/',sameSite:'lax',secure:true});res.json({ok:true})}catch(e){res.clearCookie(COOKIE,{path:'/',sameSite:'lax',secure:true});res.json({ok:true})}});
app.use('/api/applications',applicationRoutes);app.use('/api/documents',documentRoutes);app.use('/api/profile',profileRoutes);app.use('/api/approval-sync',approvalSyncRoutes);app.use('/api/disbursement',disbursementRoutes);app.use('/api/finance',financeRoutes);module.exports=app;
