import React,{useEffect,useState} from 'react';
import {useLocation,useNavigate} from 'react-router-dom';
import PortalLayout from '../components/PortalLayout';
import {applicationsApi} from '../services/applications';
import './Applications.css';

export default function Applications({user}){
 const navigate=useNavigate();const location=useLocation();const[items,setItems]=useState([]);const[loading,setLoading]=useState(true);const[message,setMessage]=useState(location.state?.created?'Application submitted successfully.':'');const[error,setError]=useState('');
 useEffect(()=>{applicationsApi.list().then(d=>setItems(d.applications||[])).catch(e=>setError(e.data?.message||'Unable to load your applications.')).finally(()=>setLoading(false))},[]);
 return <PortalLayout user={user} title="Applications" subtitle="View and manage your loan applications."><section className="applications-card"><header><div><h2>Your applications</h2><p>Track every loan request linked to your customer account.</p></div><button onClick={()=>navigate('/applications/new')}>New application</button></header>{message&&<div className="applications-success">{message}</div>}{error&&<div className="applications-error">{error}</div>}{loading?<div className="applications-empty">Loading applications...</div>:items.length?<div className="applications-list">{items.map(item=><article key={item.id||item.applicationId} role="button" tabIndex="0" onClick={()=>navigate(`/applications/${encodeURIComponent(item.id||item.applicationId)}`)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' ')navigate(`/applications/${encodeURIComponent(item.id||item.applicationId)}`)}}><div className="application-main"><span>{item.loanTypeName?.[0]||'L'}</span><div><strong>{item.loanTypeName||'Loan application'}</strong><small>{item.applicationNumber||item.applicationId||'Application'}</small></div></div><div><small>Requested amount</small><strong>₹{Number(item.requestedAmount||0).toLocaleString('en-IN')}</strong></div><div><small>Tenure</small><strong>{item.tenureMonths?`${item.tenureMonths} months`:'—'}</strong></div><div><small>Status</small><b className="application-status">{item.status||'Submitted'}</b></div><span className="application-open">View →</span></article>)}</div>:<div className="applications-empty"><span>+</span><strong>No applications yet</strong><p>Start a loan application when you are ready.</p><button onClick={()=>navigate('/applications/new')}>Apply for a loan</button></div>}</section></PortalLayout>;
}
