import React from 'react';
import {useNavigate} from 'react-router-dom';
import PortalLayout from '../components/PortalLayout';
import './Dashboard.css';

export default function Dashboard({user}){
 const navigate=useNavigate();
 return <PortalLayout user={user} title="Dashboard" subtitle="Overview of your loan activity and next steps."><section className="dashboard-hero"><div><span>WELCOME BACK</span><h2>Manage everything from one place.</h2><p>Start a new application, follow progress, upload requested documents and keep track of upcoming payments.</p></div><button onClick={()=>navigate('/applications/new')}>Start new application</button></section><section className="dashboard-stats"><article><small>Applications</small><strong>0</strong><span>No applications yet</span></article><article><small>Active loans</small><strong>0</strong><span>No active loans</span></article><article><small>Next EMI</small><strong>—</strong><span>No payment scheduled</span></article></section><section className="dashboard-grid"><article className="dashboard-panel"><header><div><h3>Recent applications</h3><p>Your latest loan applications will appear here.</p></div><button onClick={()=>navigate('/applications')}>View all</button></header><div className="dashboard-empty"><span>+</span><strong>No applications yet</strong><p>When you are ready, start your first loan application.</p><button onClick={()=>navigate('/applications/new')}>Apply for a loan</button></div></article><article className="dashboard-panel dashboard-actions"><header><div><h3>Quick actions</h3><p>Common customer tasks</p></div></header><button onClick={()=>navigate('/applications/new')}><b>01</b><span><strong>Start an application</strong><small>Choose a product and begin</small></span></button><button onClick={()=>navigate('/documents')}><b>02</b><span><strong>Upload documents</strong><small>Add supporting documents</small></span></button><button onClick={()=>navigate('/profile')}><b>03</b><span><strong>Update profile</strong><small>Keep your details current</small></span></button></article></section></PortalLayout>;
}
