import React,{useEffect,useState} from 'react';
import {useNavigate,useSearchParams} from 'react-router-dom';
import PortalLayout from '../components/PortalLayout';
import {documentsApi} from '../services/documents';
import './Documents.css';
const label=v=>String(v||'Pending Verification');
const DocIcon=()=> <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/><path d="M14 2v6h6"/><path d="M8 13h8M8 17h6"/></svg>;
const ArrowIcon=()=> <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d="M5 12h14"/><path d="m13 6 6 6-6 6"/></svg>;
export default function Documents({user}){const navigate=useNavigate();const[params]=useSearchParams();const applicationId=params.get('applicationId')||'';const[items,setItems]=useState([]);const[loading,setLoading]=useState(true);const[error,setError]=useState('');useEffect(()=>{documentsApi.list(applicationId).then(d=>setItems(d.documents||[])).catch(e=>setError(e.data?.message||'Unable to load documents.')).finally(()=>setLoading(false))},[applicationId]);return <PortalLayout user={user} title="Documents" subtitle="Upload and track documents linked to your loan applications."><section className="documents-card"><header><div><h2>{applicationId?'Application documents':'Your documents'}</h2><p>Documents are reviewed securely by the lending team.</p></div>{applicationId&&<button className="documents-upload" onClick={()=>navigate(`/documents/upload?applicationId=${encodeURIComponent(applicationId)}`)}>Upload document</button>}</header>{error&&<div className="documents-error">{error}</div>}{loading?<div className="documents-empty">Loading documents...</div>:items.length?<div className="documents-list">{items.map(doc=>{const status=label(doc.status);return <article key={doc.id}><div className="document-top"><div className="doc-icon"><DocIcon/></div><div className="doc-name"><strong>{doc.documentType||'Document'}</strong><small title={doc.fileName||doc.documentFile||''}>{doc.fileName||doc.documentFile?.split('/').pop()||'Stored securely'}</small></div><b className={`doc-status ${status.toLowerCase().replace(/\s+/g,'-')}`}>{status}</b></div><div className="document-meta"><div><small>Uploaded</small><strong>{doc.uploadedDate||'—'}</strong></div><div><small>Review status</small><strong>{status}</strong></div></div>{doc.verificationRemarks&&<div className="doc-remarks"><small>Review remarks</small><strong>{doc.verificationRemarks}</strong></div>}<button className="document-details-link" onClick={()=>navigate(`/documents/${doc.id}`)}>View document details <ArrowIcon/></button></article>})}</div>:<div className="documents-empty"><span><DocIcon/></span><strong>No documents uploaded</strong><p>{applicationId?'Upload supporting documents for this loan application.':'Open an application to upload supporting documents.'}</p>{applicationId&&<button onClick={()=>navigate(`/documents/upload?applicationId=${encodeURIComponent(applicationId)}`)}>Upload first document</button>}</div>}</section></PortalLayout>}
