import React,{useState} from 'react';
import {Link} from 'react-router-dom';
import {authApi} from '../services/auth';
import {validateField} from '../utils/validation';
import FormField from '../components/FormField';
import './Login.css';

const EyeIcon=({open})=><svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{open?<><path d="M2.5 12s3.5-6 9.5-6 9.5 6 9.5 6-3.5 6-9.5 6S2.5 12 2.5 12Z"/><circle cx="12" cy="12" r="2.8"/></>:<><path d="M3 3l18 18"/><path d="M10.6 6.2A10.7 10.7 0 0 1 12 6c6 0 9.5 6 9.5 6a16.8 16.8 0 0 1-2.2 2.8M6.1 7.2C3.8 9 2.5 12 2.5 12s3.5 6 9.5 6c1.1 0 2.1-.2 3-.5"/></>}</svg>;
export default function Login(){
  const[email,setEmail]=useState('');const[password,setPassword]=useState('');const[showPassword,setShowPassword]=useState(false);const[errors,setErrors]=useState({});const[loading,setLoading]=useState(false);const[message,setMessage]=useState('');
  function validate(){const next={email:validateField('email',email),password:validateField('password',password)};Object.keys(next).forEach(k=>!next[k]&&delete next[k]);setErrors(next);return !Object.keys(next).length;}
  async function submit(e){e.preventDefault();setMessage('');if(!validate())return;setLoading(true);try{await authApi.login({email:email.trim().toLowerCase(),password});window.location.hash='#/dashboard';window.location.reload()}catch(err){setMessage(err.data?.message||'Invalid email or password.')}finally{setLoading(false)}}
  return <div className="login-page"><section className="login-panel"><div className="login-brand"><span>L</span><strong>LMS Customer Portal</strong></div><div className="login-copy"><small>LOAN MANAGEMENT</small><h1>Manage your loan journey with confidence.</h1><p>Apply, track progress and manage repayments in one secure customer portal.</p></div><div className="login-note"><strong>Simple. Secure. Transparent.</strong><span>Everything you need, without unnecessary complexity.</span></div></section><section className="login-content"><div className="login-card"><header><span>WELCOME BACK</span><h2>Sign in</h2><p>Access your applications, documents and payments.</p></header><form onSubmit={submit} noValidate><FormField label="Email" name="email" error={errors.email}><input autoComplete="email" value={email} onChange={e=>{setEmail(e.target.value);setErrors(x=>({...x,email:''}))}} placeholder="name@example.com"/></FormField><FormField label="Password" name="password" error={errors.password}><div className="password-field"><input type={showPassword?'text':'password'} autoComplete="current-password" value={password} onChange={e=>{setPassword(e.target.value);setErrors(x=>({...x,password:''}))}} placeholder="Enter your password"/><button type="button" className="password-eye" aria-label={showPassword?'Hide password':'Show password'} onClick={()=>setShowPassword(v=>!v)}><EyeIcon open={showPassword}/></button></div></FormField><div className="login-options"><span/><Link to="/forgot-password">Forgot password?</Link></div>{message&&<div className="login-error">{message}</div>}<button className="login-submit" disabled={loading}>{loading?'Signing in...':'Sign in'}</button><p className="login-switch">New customer? <Link to="/register">Create an account</Link></p></form></div></section></div>;
}
