import React from 'react';
import {NavLink} from 'react-router-dom';
import {authApi} from '../services/auth';
import './PortalLayout.css';

const Icon=({name})=>{const common={width:18,height:18,viewBox:'0 0 24 24',fill:'none',stroke:'currentColor',strokeWidth:1.8,strokeLinecap:'round',strokeLinejoin:'round','aria-hidden':true};if(name==='dashboard')return <svg {...common}><rect x="3" y="3" width="7" height="7" rx="1.5"/><rect x="14" y="3" width="7" height="7" rx="1.5"/><rect x="3" y="14" width="7" height="7" rx="1.5"/><rect x="14" y="14" width="7" height="7" rx="1.5"/></svg>;if(name==='applications')return <svg {...common}><path d="M8 4h8"/><path d="M9 2h6a1 1 0 0 1 1 1v2H8V3a1 1 0 0 1 1-1Z"/><rect x="5" y="5" width="14" height="16" rx="2"/><path d="M8 10h8M8 14h8M8 18h5"/></svg>;if(name==='payments')return <svg {...common}><path d="M4 7h16M7 3v4M17 3v4"/><rect x="3" y="5" width="18" height="16" rx="2"/><path d="M8 12h8M8 16h5"/></svg>;if(name==='documents')return <svg {...common}><path d="M6 2h8l4 4v16H6z"/><path d="M14 2v5h5M9 12h6M9 16h6"/></svg>;return <svg {...common}><circle cx="12" cy="8" r="4"/><path d="M4 21c1.5-4 4.3-6 8-6s6.5 2 8 6"/></svg>};
const workspace=[['/dashboard','Dashboard','dashboard'],['/applications','Applications','applications'],['/payments','Repayments','payments'],['/documents','Documents','documents']];
const account=[['/profile','Profile','profile']];
export default function PortalLayout({user,title,subtitle,children}){
 async function signOut(){try{await authApi.logout()}finally{window.location.hash='#/login';window.location.reload()}}
 const email=user?.email||'Customer';const initial=email[0]?.toUpperCase()||'U';
 const link=([to,label,icon])=><NavLink key={to} to={to} className={({isActive})=>`portal-nav-link ${isActive?'active':''}`}><i><Icon name={icon}/></i><span>{label}</span></NavLink>;
 return <div className="portal-shell"><aside className="portal-sidebar"><div className="portal-brand"><span>LF</span><div><strong>LendFlow Finance</strong><small>Customer portal</small></div></div><div className="portal-nav-label">WORKSPACE</div><nav>{workspace.map(link)}</nav><div className="portal-nav-label account-label">ACCOUNT</div><nav>{account.map(link)}</nav><div className="portal-sidebar-footer"><div className="portal-secure"><b/><div><strong>Secure session</strong><small>Protected customer access</small></div></div><button onClick={signOut}>Sign out</button></div></aside><main className="portal-main"><header className="portal-topbar"><div><small>CUSTOMER WORKSPACE</small><h1>{title}</h1>{subtitle&&<p>{subtitle}</p>}</div><div className="portal-user"><span>{initial}</span><div><strong>{email}</strong><small>Customer account</small></div><button onClick={signOut}>Sign out</button></div></header><div className="portal-content">{children}</div></main><nav className="portal-mobile-nav">{[...workspace,...account].map(link)}</nav></div>
}
